In [51]:
import pandas as pd
import numpy as np

In [52]:
pd.__version__

'3.0.3'

In [79]:
df=pd.read_csv('F:\DataTalkClubs\ML_Zoomcamp\car_fuel_efficiency_2026.csv')

In [80]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Record Counts

In [81]:
len(df)

10000

### Fuel Types

In [82]:
df['fuel_type'].nunique()

3

### Missing Values

In [83]:
df.isna().any().sum()

np.int64(2)

### Max Fuel Efficiency

In [85]:
df[df['origin']=='Asia']['fuel_efficiency_mpg'].max().round(3)

np.float64(41.2)

### Median value of Horsepower (before and after filling missing values)

In [86]:
median_before=df.horsepower.median()
print('Median before:', median_before)

Median before: 254.0

In [87]:
mode=df.horsepower.mode()[0]
print('Mode:', mode)

Mode: 252.0

In [88]:
df['horsepower']=df['horsepower'].fillna(mode)

In [89]:
median_after=df.horsepower.median()
print('Median after:', median_after)

Median after: 252.0

In [90]:
if median_after > median_before:
    print('Yes, it is increased')
elif median_after<median_before:
    print('NO, it has not increased')
else:
    print('Either Both are Equal or there must be something wrong in the dataset')

NO, it has not increased

### Sum of weights

In [92]:
df[df['origin']=='Asia']

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
...,...,...,...,...,...,...,...,...,...,...,...
9984,2011,Asia,Gasoline,Front-wheel drive,3,2410,6,256.0,4610,20.2,32.4
9987,2004,Asia,Diesel,All-wheel drive,3,2180,6,266.0,4530,18.6,29.0
9990,1975,Asia,Diesel,Front-wheel drive,4,1940,6,236.0,3630,19.7,32.4
9994,1993,Asia,Gasoline,Rear-wheel drive,2,2360,6,257.0,4610,22.2,30.1
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0

In [93]:
df[df['origin']=='Asia'][['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [94]:
df[df['origin']=='Asia'][['vehicle_weight', 'model_year']].head(n=7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [95]:
X=df[df['origin']=='Asia'][['vehicle_weight', 'model_year']].head(n=7)
X

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [96]:
XTX=X.T.dot(X)
XTX

                vehicle_weight  model_year
vehicle_weight       131950500    60750580
model_year            60750580    28041424

In [97]:
XTX_inv=np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [98]:
y=np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [99]:
w = XTX_inv.dot(X.T).dot(y)
w

array([0.13644777, 0.2327492 ])

In [100]:
w.sum()

np.float64(0.36919696904927707)

In [101]:
XTX=X.T @ X
XTX_inv=np.linalg.inv(XTX)
w=XTX_inv @ X.T @ y
w.sum().round(3)

np.float64(0.369)