# Introduction to ML

### Linear Regression

In [ ]:
# Features (year, make, model) +Model--> Prediction

### Machine Learning vs Rule-Based Systems

#### Spam detection system

In [8]:
# If sender=promotion@online.com ='spam'
# elif: 'tax review' in title: and 'online.com' in sender domain=spam
# else 'good email':
def detect_spam(email):
    if email.sender=='promotions@online.com':
        return spam
    if contains(email.title, ['tax', 'review']) and domain(email.sender, 'online.com'):
        return spam
    if contains(email.body, ['deposit']):
        return spam
    return Good
# it goes on and on

#### We use machine learning instead

In [10]:
# Users define the features
# Getting data --> define & calculate features --> train and use the model
# Start with the rules and then use these rules as features (for Rule Based Systems)
# [1,1,0,0.1,1]
# Length of title>10? True
# Length of the body >10? True
# Sender promotion@online.com? False
# Sender hpYOSKmL@test.com? False
# Sender domain 'test.com'? True
# Email body contains 'deposit'? True
# Because some User X marked it spam, so we also mark it as spam, and we train our ML model on this 
# We have some predictions then we have to make final decision
# We have to decide which email should go to spam or not, 
# so everything with a probability >=0.5 =='spam', i.e., threshold
# Data --> ML --> Outcome (spam or not)

### Supervised ML

In [11]:
# Spam prediction
# Car price prediction
# Feature Matrix represented by 'X'
# for each X we have a corresponding 'y'
# 'g' is nothing else but our model, and that is approximately close to 'y'.
# model(features)\approx y
# Output from the spam prediction model was probability.
# The process of loooking at the features and coming up with this function 'g' is called TRAINING.

In [14]:
# Regession problem (anything that output number is called Regression)
# Classification --> We input the image and the output is a category.
    # Binary Classification --> Spam or not
    # Multiclass Classification--> As long as its more than 2.
# Ranking --> Is usually used in cases when you want rank something. E.g, Recommendation System, Page Ranking System
# In summary--> coming up with a function 'g' that is close to the target value.

#### CRISP -DM-- > cross industries standard processing data  mining

In [15]:
# From data collecting to deployment
# Business Understanding--> Data Understanding--> Data Preparation--> Modeling-->Evaluation--> Deployment
# Identify the business problem (The question here is: do we really need ML here?)
  ## Is it all Users or only one User who is complaining?
   # Reduce the number of spam messages
   # Reduce the amount of complaints about spam
  ## The final goal has to be measurable, like e.g, we want to reduce the amount of spam by 50%.
# What data is really available for this case --> is the dataset large enough? Do we need more data or is it enough?
# Identify the data sources--> It may influence the goal or may we go back to the previous step and adjust it?
# Data preparation--> Transform the data so it can be put into a ML model--> clean the data, build the pipeline,
  # convert into a tabular form
# Modeling--> Train the model: the actual ML happens here
    # We try different models and we select the best one.The main here is: which model to choose?
    # Sometimes we might need to go back to the data preparation step.
# Evaluation--> Measure how well the model solves the business problem
    # Is the model good enough? Do our metrics improve?
    # Was the goal achieveable ? or did we set it too high from the start? Then we have to go back again and change our goal.
# Deployment--> deploy the model to production
    # Online evaluation--> evaluation of live users
    # proper monitering is required here
    # ensuring the quality and maintainability
    
# ML projects require many iterations!

### Modeling Step--which model to choose?

In [ ]:
# Selecting the best model
    # Holdout + training
    # We use 80% of the data for training
    # The rest 20% is used for validation
    # Validation (V)--> g(\hat(X_v))=\hat(y_v)\approx y_v
# Select the model which has the best accuracy
# Multiple comparison problem 
    # The model can just get lucky 
##    # That's where Cross Validation comes in!
# 60% Training -- 20% Validation -- 20% Testing
# We take only the model that was performing well, we use only that model, and then test it on the test dataset.
# Split your dataset in train (60%), validation (20%), and test (20%) datasets.
    # perform model selection on the validation dataset
# We combine the Training + Validation

### Introduction to Numpy

In [3]:
import numpy as np

In [155]:
print(np.zeros(5))
print(np.ones(5))
print(np.full(10, 2.5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]

In [156]:
a=np.array([1,2,3])
print(a)
a=np.arange(10)
print(a)

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]

In [157]:
a=np.linspace(0,100,11)
print(a)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]

In [158]:
a=np.zeros((5,2))
print(a)
a=np.array([[1,2,3],[4,5,6], [6,7,8]] )
print(a)
a[0,1]=10
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[ 1 10  3]
 [ 4  5  6]
 [ 6  7  8]]

In [159]:
a[:,1], a[1:,]

(array([10,  5,  7]),
 array([[4, 5, 6],
        [6, 7, 8]]))

In [160]:
np.random.seed(2)
a=np.random.rand(5,2)
print(a)

[[0.4359949  0.02592623]
 [0.54966248 0.43532239]
 [0.4203678  0.33033482]
 [0.20464863 0.61927097]
 [0.29965467 0.26682728]]

In [161]:
np.random.seed(2)
b=np.random.randint(low=0, high=100, size=(5,2))
print(b)

[[40 15]
 [72 22]
 [43 82]
 [75  7]
 [34 49]]

In [162]:
a+b

array([[40.4359949 , 15.02592623],
       [72.54966248, 22.43532239],
       [43.4203678 , 82.33033482],
       [75.20464863,  7.61927097],
       [34.29965467, 49.26682728]])

### Linear Algebra Refresher
    . Vector Operations
    . Multiplications
        . Vector-vector multiplication
        . Matrix-vector multiplication
        . Matrix-matrix multiplication
    . Matrix Inverse
    . Identity matrix

In [33]:
a=np.array([2,4,5,6]) 
print(a)

[2 4 5 6]

In [34]:
print(a*2)
print(a+2)
b=np.array([3,4,5,7])
print(b)
print(a+b)

[ 4  8 10 12]
[4 6 7 8]
[3 4 5 7]
[ 5  8 10 13]

In [35]:
print(np.dot(a,b))
## \sum u_i v_i
def vec_vec_multiplication(u, v):
    assert u.shape[0]==v.shape[0]
    n=u.shape[0]
    result=0.0
    for i in range(n):
        result=result+u[i]*v[i]
    return result

89

In [36]:
print(vec_vec_multiplication(a,b))

89.0

In [37]:
a=np.array([[2,4,5,6],[1,2,1,2],[3,1,2,1]])
# v=np.array([1,0.5,2,1])

In [38]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1]==v.shape[0]
    
    num_rows=u.shape[0]
    
    result=np.zeros(num_rows)
    
    for i in range(num_rows):
        
        result[i]=vec_vec_multiplication(u[i], v)
   
    return result

In [39]:
print(matrix_vector_multiplication(a,b))
# print(np.matmul(a,v))

[89. 30. 30.]

In [40]:
v=np.array([[1,0,0,2], [1,0.5,2,1], [2,1,1,0]])
print(v.shape)
print(v.T.shape)
# print(np.delete(v, [0], axis=1), np)
# print(np.delete(v, [0], axis=1))
# print(v.shape)

(3, 4)
(4, 3)

In [41]:
def matrix_matrix_multiplication(u,v):
        assert u.shape[1]==v.shape[0]
        
        num_rows=u.shape[0]
        num_cols=v.shape[1]
        
        result=np.zeros((num_rows, num_cols))
        
        for i in range(num_cols):
            vi    = v[:,i]
            uvi   = matrix_vector_multiplication(u,vi)
            result[:,i]=uvi
            
        return result

In [42]:
print(matrix_matrix_multiplication(a,v.T))
print(a.shape)
print(v.T.shape)

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]
(3, 4)
(4, 3)

In [43]:
print(np.matmul(a,v.T))
print(a.dot(v.T))

[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]
[[14.  20.  13. ]
 [ 5.   6.   5. ]
 [ 5.   8.5  9. ]]

#### Matrix Inverse

In [44]:
v=np.delete(v,1,1)
print(v)

[[1. 0. 2.]
 [1. 2. 1.]
 [2. 1. 0.]]

In [49]:
vs_inv=np.linalg.inv(v)
print(vs_inv.shape)
print(vs_inv.dot(v))

(3, 3)
[[ 1.00000000e+00 -1.11022302e-16 -5.55111512e-17]
 [ 5.55111512e-17  1.00000000e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

## Pandas

In [50]:
import pandas as pd

In [107]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [108]:
df=pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [109]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [110]:
df[['Make', 'Model', 'MSRP']]

      Make     Model   MSRP
0   Nissan    Stanza   2000
1  Hyundai    Sonata  27150
2    Lotus     Elise  54990
3      GMC    Acadia  34450
4   Nissan  Frontier  32340

In [111]:
# Creating new column
df['id']=[1,2,3,4,5]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [112]:
# deleting a column
del df['id']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [113]:
# accessing elements witin a df
df.loc[[1,2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [114]:
## accessing elements positionally
df.iloc[[1,2]]
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [116]:
df=df.reset_index(drop=True)
# df=df.drop(['index'])
# del df['index']
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [117]:
# Give all the cars manufactures after 2015
df[df['Year']>=2015]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [119]:
# String operations
df['Vehicle_Style'].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [126]:
df['Vehile_Style']=df['Vehicle_Style'].str.replace(' ','_').str.lower()
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,Vehile_Style
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,sedan
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,sedan
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,convertible
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4dr_suv
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,pickup

In [129]:
df.describe().round(2)

          Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

In [130]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        5
MSRP                 5
Vehile_Style         4
dtype: int64

In [132]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
Vehile_Style         0
dtype: int64

In [133]:
## Group by
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [134]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340], dtype=int64)

In [135]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'Vehile_Style': 'sedan'},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'Sedan',
  'MSRP': 27150,
  'Vehile_Style': 'sedan'},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'Vehile_Style': 'convertible'},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr SUV',
  'MSRP': 34450,
  'Vehile_Style': '4dr_suv'},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'Pickup',
  'MSRP': 32340,
  'Vehile_Style': 'pickup'}]